### ISSUE TITLE
What is the problem caused by this error report?

### ISSUE THREAD

**Issue by ScottishFold007** [vicgalle/stable-diffusion-aesthetic-gradients#3]
![image](https://user-images.githubusercontent.com/36957508/195111166-e4afb676-264c-413d-bc83-85cb8d396690.png)

**Comment by vicgalle** [comment]
Hi @ScottishFold007 . It seems to me that your environment is not properly configured. Did you run the following commands first?

```
conda env create -f environment.yaml
conda activate ldm
pip install -e .
```

If the previous commands execute successfully, then you would be able to run the sample commands in the README without problems
