### ISSUE TITLE
RuntimeError: torch.cat(): expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by rikkar69** [vicgalle/stable-diffusion-aesthetic-gradients#9]
Hello, getting this error when running gen_aesthetic_embeddings.py. I created the folder of images in the reference_images folder, any ideas what could be the issue?

**Comment by vicgalle** [comment]
It seems to me that your variable `image_paths` is empty. Check you are reading the correct directory and that the images are indeed there

**Comment by rikkar69** [comment]
i moved the script to 'stable-diffusion-aesthetic-gradients' folder and it generated the embedding file, that was an easy fix. thanks!
